#!/usr/bin/env python3
# return a jsonified str of the x509 for a given url

import sys
import json
import requests

if len(sys.argv) < 2:
    print("usage: certinfo <url>")
    sys.exit(1)

with requests.get(sys.argv[1], stream=True) as response:
    certificate_info = response.raw.connection.sock.getpeercert()
    subject = dict(x[0] for x in certificate_info['subject'])
    issuer = dict(x[0] for x in certificate_info['issuer'])
    subjectAltName = [x[1] for x in certificate_info['subjectAltName']]
    certificate_info['subjectAltName'] = subjectAltName
    certificate_info['subject'] = subject
    certificate_info['issuer'] = issuer
    print(json.dumps(certificate_info, indent=4))
