#!/bin/bash
# run a command line chrome that prints full dom after js processing

sysinstall="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
userinstall="~/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

# if no $1 beginning with http
test -z "$1" && echo "usage: $0 <url>" && exit 1

if [ -f "${sysinstall}" ]; then
  "${sysinstall}" --enable-logging --headless --disable-gpu --no-sandbox --disable-setuid-sandbox --dump-dom "${1}" 2>/dev/null
elif [ -f "${userinstall}" ]; then
  "${userinstall}" --enable-logging --headless --disable-gpu --no-sandbox --disable-setuid-sandbox --dump-dom "${1}" 2>/dev/null
else
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "do u want to install google-chrome-stable (y/n)"
        read -r answer
        if [[ $answer =~ ^([yY][eE][sS]|[yY])$ ]]; then
            brew install --cask google-chrome
        fi
    fi
fi