#!/bin/bash
# open a domain in browser sessions for cybertasks

if [ -z "$1" ]; then
    echo "usage: ci-domain domain"
    exit 1
else
    domain=$1
fi

open "https://www.virustotal.com/graph/${domain}"
open "https://securitytrails.com/domain/$domain/dns"
open "https://dnsmap.io/#A/$domain"
open "https://instantdomainsearch.com/domain/extensions?q=$domain"
if [[ $domain == *.nz ]]; then
    open "https://dnc.org.nz/whois/whois-lookup/?domain_name=$domain#Form_show"
fi