#!/bin/bash
# open an ip in browser sessions for cyebrtasks
if [ -z "$1" ]; then
    echo "usage: ci-ip ip"
    exit 1
else
    ip=$1
fi

open "https://www.shodan.io/host/${ip}"
open "https://app.binaryedge.io/services/query/${ip}"
open "https://www.virustotal.com/gui/ip-address/${ip}/detection"
open "https://viz.greynoise.io/ip/${ip}"
