#!/usr/bin/env python3
# fetch incoming auckland port ship data

import requests
import bs4
import json
import argparse
import sys
parser = argparse.ArgumentParser()
parser.add_argument("-j", "--json", help="json output", action="store_true")
parser.add_argument("-c", "--csv", help="csv output", action="store_true")
if not len(sys.argv) > 1:
    parser.print_help()
    exit()
shipstatusuri = 'https://www.poal.co.nz/operations/schedules/cruise'
try:
    shipstatus = requests.get(shipstatusuri)
except requests.exceptions.RequestException as e:
    print(e)
    exit(1)
if shipstatus.status_code != 200:
    print('error fetching ship status')
    exit(1)
table = bs4.BeautifulSoup(shipstatus.text, 'html.parser').find('table', {'class': 'makeResponsive vessels cruiseSchedule'})
if parser.parse_args().json:
    cruises = []
    for row in table.find_all('tr'):
        cols = row.find_all('td')
        if len(cols) > 0:
            cruises.append({'vessel': cols[0].text.replace('\n', ' ').replace('\t', ' ').strip(),
                            'wharf': cols[1].text.replace('\n', ' ').replace('\t', ' ').strip(),
                            'arrives': cols[2].text.replace('\n', ' ').replace('\t', ' ').strip(),
                            'departs': cols[3].text.replace('\n', ' ').replace('\t', ' ').strip(),
                            'previous': cols[4].text.replace('\n', ' ').replace('\t', ' ').strip(),
                            'next': cols[5].text.replace('\n', ' ').replace('\t', ' ').strip()})
    print(json.dumps(cruises, indent=4))
if parser.parse_args().csv:
    for row in table.find_all('tr'):
        cols = row.find_all('td')
        if len(cols) > 0:
            print(cols[0].text.replace('\n', ' ').replace('\t', ' ').strip() + ',' +
                  cols[1].text.replace('\n', ' ').replace('\t', ' ').strip() + ',' +
                  cols[2].text.replace('\n', ' ').replace('\t', ' ').strip() + ',' +
                  cols[3].text.replace('\n', ' ').replace('\t', ' ').strip() + ',' +
                  cols[4].text.replace('\n', ' ').replace('\t', ' ').strip() + ',' +
                  cols[5].text.replace('\n', ' ').replace('\t', ' ').strip())
