#!/bin/bash
# get a shell in the latest built docker container
set -e
latestcontainer=$( docker ps -q -n1 )
if test ! -z "$1" ; then
  echo searching SHELLs on "$1"
  docker exec "$1" ls /bin/ash &>/dev/null && docker exec -it -u root "$1" ash
  docker exec "$1" ls /bin/bash &>/dev/null && docker exec -it -u root "$1" bash
elif docker ps | grep "$latestcontainer" >/dev/null ; then
  echo searching SHELLs on "$latestcontainer"
  docker exec "$latestcontainer" ls /bin/ash &>/dev/null && docker exec -it -u root "$latestcontainer" ash
  docker exec "$latestcontainer" ls /bin/bash &>/dev/null && docker exec -it -u root "$latestcontainer" bash
  echo
else
  echo ERROR: no running containers >&2
  exit
fi
