#!/bin/bash
# get logs of the latest or specified container

if test ! -z "$1" ; then
  docker logs -f --tail 1000 "$1"
else
  latestcontainer=$( docker ps -q -n1 )
    if docker ps | grep "$latestcontainer" >/dev/null ; then
    docker logs -f --tail 1000 "$latestcontainer"
  else
    echo ERROR: No running containers >&2
    exit
  fi
fi
