#!/bin/zsh
# make emoji matrixrain
matrixpath="${0:a:h}/matrix"
echo "press Q or ctrl-c to exit"
if [[ ! -f "${matrixpath}" ]]
then
curl -s -L "https://raw.githubusercontent.com/will8211/unimatrix/master/unimatrix.py" -o "${matrixpath}"
fi
if [[ ! -x "${matrixpath}" ]]
then
    chmod +x "${matrixpath}"
fi
if [[ $(sha256sum "${matrixpath}") != "78d0d725acf35e10cb2b3acbc458935f25e87c5b516b2e9337ede1efba273bd2  ${matrixpath}" ]]
then
    echo "matrix script failed checksum validation!"
    exit 1
fi
emojiUrl="https://api.emojisworld.fr/v1/random?limit=100"
emojiList=`curl -s "${emojiUrl}" | jq -r -c '.results[].emoji' | tr -d '\n'`
"${matrixpath}" -o -f -s 90 -a -u "${emojiList}"
