#!/bin/bash
# initalise and update submodules within a git repository (git submodule init & update)

if [[ -z "$(git rev-parse --git-dir 2>/dev/null)" ]]; then
  echo "not in a git repo"
  exit 1
fi

git submodule init
git submodule update -j 20 