#!/bin/bash
# make google query from terminal

if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "only works on macOS, sorry"
  exit 1
fi

if [[ $# -eq 0 ]]; then
  printf 'search query: ' && read query
else
  query="$*"
fi

query=$(echo $query | sed 's/ /%20/g')
open "https://google.com/search?q=${query}"
