#!/bin/bash
# query IP API for any IP details using ipinfo.io (HTTPS supported)

if [ -z "$1" ]; then
    echo "usage: ipi <ip-address>"
    exit 1
fi

timeout 1 curl -s "https://ipinfo.io/${1}/json" -H "User-Agent: curl/7.54"
