#!/bin/bash
# healthcheck a kubes service or all services

if [[ "$1" == "all" ]] || [[ -z "$1" ]] ; then
  sitelist=$( kubectl get deployments -n mdr | grep "1/1" | cut -d ' ' -f 1 | grep -v "op-scim" )
  sitecount=$( wc -l <<< "${sitelist}" )
  currentsite=1
  while read site && [[ "$sitelist" != "\n" ]] ; do
    echo "Showing (${currentsite}/${sitecount}):" >&2
    ((currentsite++))
    kubectl exec deploy/$site -n mdr -- curl -s localhost:8080 2>/dev/null | jq .
    if [[ "$1" != "all" ]] ; then
      read meh </dev/tty
    fi
  done <<< "$sitelist"
else
  kubectl exec -n mdr -i --tty deploy/$( ks $1 ) -- curl -s localhost:8080 | tail | jq --color-output .
fi
wait
