#!/usr/bin/env python3
# simple webserver to validate ownership checks (used for Splunk HEC with Meraki Local Analytics API)

import sys
import http.server

if len(sys.argv) != 3:
    print("usage: mock-vaildate-endpoint <port> <response>")
    exit()

port = int(sys.argv[1])
body = bytes(sys.argv[2], 'utf-8')

class Handler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        print(self.headers)
        self.send_response(200)
        self.send_header('Content-type', 'text/plain')
        self.send_header('Content-length', len(body))
        self.end_headers()
        self.wfile.write(body)

server = http.server.HTTPServer(('0.0.0.0', port), Handler)
server.serve_forever()
