#!/bin/zsh
# get basic stats of a pihole instance from the php api

if [[ -z $(dig +short pi.hole) ]]; then
  echo "error: could not resolve pi.hole"
  exit 1
fi

if [ ! -f ~/.dnsauth ]; then
  echo "error: pihole api access key missing from ~/.dnsauth"
  exit 1
else    
  authkey=$(cat ~/.dnsauth)
fi

pihole_apibase="http://pi.hole/admin/api.php"

curl -s "${pihole_apibase}" | jq

curl -s "${pihole_apibase}?getQueryTypes&auth=${authkey}" | jq

curl -s "${pihole_apibase}?getQuerySources&auth=${authkey}" | jq

curl -s "${pihole_apibase}?topItems&auth=${authkey}" | jq

curl -s "${pihole_apibase}?getForwardDestinations&auth=${authkey}" | jq