#!/bin/zsh
# show the last domain blocked by pihole

if [ ! -f ~/.dnsauth ]; then
  echo "error: pihole api access key missing from ~/.dnsauth"
  exit 1
else    
  authkey=$(cat ~/.dnsauth)
fi

pihole_apibase="http://pihole.nameserv/admin/api.php"

curl -s "${pihole_apibase}?recentBlocked&auth=${authkey}"

echo
