#!/bin/zsh
# get basic stats of a pihole instance from the php api

if [ ! -f ~/.dnsauth ]; then
  echo "error: pihole api access key missing from ~/.dnsauth"
  exit 1
else    
  authkey=$(cat ~/.dnsauth)
fi

pihole_apibase="http://pihole.nameserv/admin/api.php"

curl -s "${pihole_apibase}" | jq

curl -s "${pihole_apibase}?getQueryTypes&auth=${authkey}" | jq

curl -s "${pihole_apibase}?getQuerySources&auth=${authkey}" | jq

curl -s "${pihole_apibase}?topItems&auth=${authkey}" | jq

curl -s "${pihole_apibase}?getForwardDestinations&auth=${authkey}" | jq