#!/bin/bash
# return ransomwatch groups

if [ -n "$1" ]; then
  curl -sL ransomwhat.telemetry.ltd/groups \
  | jq -r ".[] | select(.name == \"$1\") | .locations[]"
else
  curl -sL ransomwhat.telemetry.ltd/groups \
  | jq
fi
