#!/bin/zsh
# show duplicate lines within a file

if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "script for macOS - just use 'uniq -cd'"
    exit 1
fi

if [ -t 0 ]; then
    echo "usage: cat file.txt | showdupes"
    exit 1
fi

uniq -c | grep -v '^ *1 '
