#!/bin/bash
# check if a given credit card number (var1) passes mod10 checksum

if [ -z "$1" ]; then
    echo "usage: validpan <credit-card-number>"
    exit 1
fi

pan=$1
panlen=${#pan}

for i in $(seq $((panlen - 1)) -1 0); do
  digit=${pan:$i:1}
  if [ $(((panlen-i) % 2)) -eq 0 ]; then
     #even
     ((digit*=2))
     [ ${#digit} -eq 2 ] && digit=$((${digit:0:1}+${digit:1:1}))
  fi
  ((sum+=digit))
done

if [ $((sum % 10)) -eq 0 ]; then
    echo "Luhn Mod10 Check Passes"
    exit 0
else
    echo "Luhn Mod10 check Fails"
    exit 1
fi
