#!/bin/bash
# search for common port usages (what does port X typically correspond to)

if [ -z "$1" ]; then
    echo "usage: whatport <port>"
    exit 1
fi

curl -s "https://isc.sans.edu/api/port/${1}?json" \
-H "User-Agent: curl/7.54" \
| jq .services
